#----------------------------------------------------------------------
# This file was generated by C:\Users\ÁõÖ¾¾ü\AppData\Local\Programs\Python\Python39\Lib\site-packages\wx\tools\img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

Launch = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAARnQU1B'
    b'AACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAa8SURBVFhHnVddbBRVFD7zs7uz3elu'
    b'S1usyJ8ETXzyJyEGTAwGxEhEw4PRaDBRjDE+GH3ghYQiGH3xgRBfiBGJGh+MiZqAGg31Bw1g'
    b'TFAjkkBbRH4Eacv+ze7MzszueL6ze9vZbavSL3zduzv3nHPvN+fec9CODT0SUQeiep2shYsp'
    b'YZh04uiw/HbXmnUU1EPyrl4kzTDkt7lwPfZ663MKMI4adUokU8JapSRU3/EMc+bC9dq3KYAH'
    b'6cFlZJom/Th8kBpBjR7cvl+effH6VtITKbp73SYKw5DcK3/OUGI+9lMKqJXDGNLBOAprFLiO'
    b'EGP8hmeYo3bSxnnYiwIYzLZyGObPn5EF9i69lRJpu20ngV+TZwqQ+Hrt9X9feYW6u7PClKFR'
    b'ivWy0xZl0inqTSeFOatJ9R3PMAdzYaPs4atTCVA7sff5aK6Vw3DH7p1k27YsEkhmspTUNfrq'
    b'7FUyNI0WZ5Ly+8WKT/Uoog0rFpLfiMjnxAM03SDHcejVoV1ULpfalEixL12thLOANP7btvNs'
    b'jqKgQpFfIaqz3Ey/NC6MPA4A1prU/DJpNYdCZ5LC8gTpDV+ohS5pdVd8xZVALIn57hO3RYHv'
    b'0aoNj1PgVUgfWEq2ZcnOEXzfcZecPDvmzI0jabDG7MX1+D1qOrnVCmmsCHbfiUyun4YeHqDI'
    b'SIsSjudRY/w8q2OSrpsJMsymjIBupkjjJIHsdsYmp1BhjpNbvsbMT7FYmKQS0ykySzzmT9Dj'
    b'eXHWnDyzIL7gE74RQ8Fc1NNNhp6lE19/TI3Qp9vv3UQev2NelezIrVbJ930aGTnNiTrbDdgU'
    b'E3M7obOfYrFMlj3O7kwK2ad37iSFrNKvRw6SybmnQ1pQYxV0ZsLKcJJkWi4Y7BjOcUpMViuR'
    b'WyDEGEz2DwgNvlTAXKZPiLHOCSinK8FzeTEmrxG+EQOxQDO3cJFMXEwXeXJOlEgndDnTgdda'
    b'RAtappuKu1+WcW5oD8tp0pVN98r3wYNHqMuLaNv7D8j3N7Z8SVW/RE6FE9i0aDTvUpRK0m/f'
    b'fUqOX6ebBweozkroUaNBDT5inUrgqEmi8dHif/OGKMMbTOq6+INvxJiKp2qBxhOgRImrFS6U'
    b'LZ+NUd2ZoOEfrkpynT59SiSHCkBUKcun3tMrn41CXj5tq0c+Ha8g8p/8/RRlc3301p4XKDBt'
    b'OrBxBeVdn7JcLbHx6VoQUwJl08R7R2J15Fbd14UKftUVKhT4QIEKeP+gAnwjBmIh5rQnBn7o'
    b'GVzCq1tCi9KcF3ZSznmthjtfo0YiR/3HHhNiHCYtuuXzD4QYh9keWvnUQ0KMIf/oyBidOTNG'
    b'y3Jp8QnfiIFYQNsCgEYQyHFU4DMw6xH7v5AciB1f+EYMhXYFWlXRHlxOF8qu3O+4EhT0oEgT'
    b'qz8UYmzyDTqy8UkhxmapQKPvHRJirKDzBuALPuEbMRBLnslfRrwqgigsdVYJu48rYNmGcC6Y'
    b'fGmBncCRg0/lX/UDqEJTO8cDVEWUVFS10DEoX3bI47OMRSR7F9Dh+1aJw/Xf/ETVSlXePyAq'
    b'8ElyD+yR7+mn+b6ImrsMeCdrl+Qo0Lvo++FDVHFr/9EPBH6zpLJhpwLzRVBnf+wTvuP9gCnd'
    b'a0c/gGbi8EvPzshQP39Ndq7GkA87B5ADgOwc8KrckUwXHQA9wvrX3qYav9oZ/YDsXHVCXJY7'
    b'gcICJcJiQajeZUaLhCkOJmTZhTy2rPYFAPAd74xM9O1omzs7IXQy1DyqEhhVDQFxt+NoTU5O'
    b'ygWDc47vc8Hi3kIBPisTl6Uzun/bPrkLZvQDuJKljXI9qnDjgGYikxvgzO+ldPcCsvlatbN9'
    b'cr2CGOO3bE+/EHPi1BJdzIz4A+EbMRS04RfviQyWd+zCJe64qrTmmZ2SnebEOWkgtu99kzK8'
    b'C9RzlFRUNRSWv9xmh4QbDpCekJNMsp0TLg4E3vHcVukNw/7lknNH39klpXmqHzC4UTSZUq+Z'
    b'TsURgyjZzWW0m5uJNIW6xWPuEy0OwoUFdMkSepQmV0vLUfONLqrUWe4Wq0z4gk/lH7FA7fgr'
    b'myNVBfGOz166LEqs3rqLQlbC+HuU/wcj14V0MKjnKKnL+7LNy6pVq9Ehg2MTRblu71i7WeyB'
    b'iAtQ/YaVYn9s/04yUl204qYbZ+8HdH6ICZAJBsgDsMaygmgmykyU1HzVp5IbCDHGb9WgQS5T'
    b'zVf28AWf8I0YKt6s/YBSAju5c92jsotfvv1Edo5OBoaqnscRt//jyviUEsDPwx+JPXYet5+u'
    b'BS0l5M5mqnelgB2A6rmq53HG7dV8BeWv3b5B/wBdTaQkNlcM3AAAAABJRU5ErkJggg==')

