#----------------------------------------------------------------------
# This file was generated by C:\Users\ÁõÖ¾¾ü\AppData\Local\Programs\Python\Python39\Lib\site-packages\wx\tools\img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

Settings = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAARnQU1B'
    b'AACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAYlSURBVFhHxVbNb1RVFD/zZubNTGem'
    b'0w+YQtwoCbIoKZgQxKiJsjBsGjaICBvcEBYmkgh7F26M/0QrIMZIQggrdQELwBQJNYYQ05aW'
    b'1vIxpbSdmZb5fp7f782ZmY7DlxvPyy/33ffuPR+/e+65N3D16lUvGAzK9My0RCIRmZqcklAo'
    b'JBC04+Pjgv+pVIrfVlZW2Hbqe57H90AgwO9ra2ty8uRJKRQKHfVDHCgHuruTRCwWk2g0ykHh'
    b'cJj/gLDr+tBvQCTiEhjHsS3/Wt+fpx8InPvhnIcfX3z+pSSSSentjUu5XJHB7dsZ0ezsLAeu'
    b'ra6K4ziSzxcZoefVFIg8xrZWq9Vj8hnAuHw+L998+zW/ddJfqVTEAS0AfiYSCb4DQSeknvte'
    b'Aq5G5bp+RCEwEgrzu0Vo43z434Dn6gd27dr11cryikxPT0hXV0Q2bkxLxI1K+vUeiSVduTcx'
    b'x2j9qD3p6euWrniUiCdiuoa+E329vTq/i4jH4xJyHerr7emTxceLHfWHY06TgVKxLMVCmW25'
    b'VCY9pEhpd5wAaYR4NU/pbgL/AoAOAeAkUKvW+P9F+gMnTpzQFQyIm1IlagBrWa1V5bXUG+Jq'
    b'ko1+d4ZJ090d5VpbpkNgMJstiKMvNRjVuelNfTQOx8vlsgwODnLNO+lH6zBbdT11PGlurGkY'
    b'mR3kBKBSrdJji7AVMA4nCDKmyuhgQGmPcVna9YM1snfs2DEPTvx27XduGwgM9qdTUq1UZSC9'
    b'UT2tSV88wX+LuVzDAER1UnFWMx7f1/Kr7Nu/J0/ybMXzv0HAzO49b5GZhibQHYlir2Mfh0k7'
    b'oMHV191nwmDRm2AMAOPmAAS7AgyHwWgdYNdxgnQ4cOrUKQ8F5ddfLutPt77WfoJB/PeabNiw'
    b'gS0nqYGsMhHU7ZZ5+IR9qwd4x5yoFhy0rQlsgsiHhobIhGPGMNmMoV8sFolSqURY1lrfUNXc'
    b'AKAUCu073v2+D+hsosliQGs1c+DG2BjpiURjrN37h/dLQR0wwYRWQWRg48HD+9oGqaxV/Ogd'
    b'WVpaUr1hmZpqngFwDAwgIE1cXTMdaJFjIp5CsaAMFPRQWSZyuew64LABlpaWaQRltxWrWrrR'
    b'GkOteYF3W0ruAmyLubk5bg8IjO/7aB8NHPj4ABl5lti2mpyaZE60SkzZPHvmLMvwX3fuNBhA'
    b'5G9u2+YzAE/oTX1fGrUGeA92LAdw7ALWR30HmC/FkiQTScJywKSp2wdYpw37iWx+nFkmFhdW'
    b'uLaZhYyMaW7cGLsh92bvSS6fk61btxJ4t/6WLVtkYGBA+vv7Ze+Hewmv6slCZsE3ouyjYuZy'
    b'RcKvnvRLHPM0r9sKCley/tpWWctrjC6eiJNeWyKIUf8saWURyGVbckjfzW5o586dpPLo0c9I'
    b'YzqdprErl6/Q+KVLl+jI4SOH66pfXmB4IZORhw+qcub7USYlBLvi+vXrzIlGJcT1CaBnum/N'
    b'Q/8e4NZHNcUiM2nvm9h32xm2O0xCuPPBkMnIyAgjHh4ern/pLFjfVmnvtwqW6u7du/L06VP2'
    b'cTzfvHmTrX8aKvybTKhxoUApZTlFbVC0R/iifjik54rCBPdEMAkbcMjsruMMRahXbzabNm+W'
    b'06OjcnpkVG8uvdKzOa67JCO3/7wtMzMzxKNHj4hO/fn5+3Lh5x/l2vgVOgGD83N/K+bXOQlZ'
    b'31Ox/e1fr+L1k1BvNnqNAmX5nK6hwtWDC+jcz9OwiwjrzDgBv9a0757A8ePHPeQAd0NVD5tC'
    b'iVfn8+d/0klB2f2Bntsl/V4ucYLlC+iDPKsfV+fDbkjGLt/S+0RFd9ERVth8Vp3TsROTE/4u'
    b'sIrEuqxAAqIGmOf+/SCkeYHc6JKenhQRi0WJ5n1/fT8Ycv5VmiHMNb3Iwi7xycGDHo7P9959'
    b'n1HCiUgkKhcvXuCFBJfIdoGTqBdoXyRuJMzjec/b70i5ogVvLc+lGr91y09Ci9RgYvcBCeCW'
    b'8d9heky/Md3of3roEHNgaMcOMpCMJ+kAvEWyoCxjQru8TPTYVTi4MNZyCMmIZfhD68+6bciK'
    b'V89kAJOeh1cV0wvjlrAQMoAXy1672VjUnaJ/FTF97WJONBz4f0TkHzOdFjHMYzwCAAAAAElF'
    b'TkSuQmCC')

