name: GitHub Actions Test
on:
  push

jobs:
  Use-Nuitka_PackUp:
    runs-on: windows-latest
    steps:
    - name: Print a greeting
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Mona
        MIDDLE_NAME: The
        LAST_NAME: Octocat
      run: |
        python -m pip install nuitka
        dir
  
